[package]
name = "rustmcp"
version = "0.1.0"
edition = "2021"
description = "A Model Context Protocol (MCP) server implementation in Rust"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[dependencies]
rust-mcp-sdk = { version = "0.4.5", default-features = false, features = ["server", "2025_03_26"] }
tokio = { version = "1.45.1", default-features = false, features = [] }
