[package]
name = "rustmcp"
version = "0.1.0"
edition = "2024"
description = "A Model Context Protocol (MCP) server implementation in Rust"
authors = ["Vaiz"]
license = "Unlicense"

[package.metadata.cargo-machete]
ignored = ["serde_json"]

[package.metadata.docs.rs]
# Enable documentation generation features
all-features = true

[[bin]]
name = "rustmcp"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.88"
clap = { version = "4.5.40", features = ["derive"] }
rust-mcp-sdk = { version = "0.4.5", default-features = false, features = ["server", "2025_03_26", "macros"] }
serde = { version ="1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", default-features = false, features = [] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }


