[package]
name = "rust-mcp-server"
version = "0.1.0"
edition = "2024"
description = "An MCP server for Rust development"
authors = ["Vaiz"]
license = "Unlicense"

[dependencies]
async-trait = "0.1.88"
clap = { version = "4.5.40", default-features = false, features = ["std", "help", "error-context", "usage", "suggestions", "derive", "string"] }
rust-mcp-sdk = { version = "0.4.5", default-features = false, features = ["server", "2025_03_26", "macros"] }
serde = { version ="1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", default-features = false, features = [] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[package.metadata.cargo-machete]
ignored = ["serde_json"]
