name: Build and Upload Release Binaries

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - target: x86_64-pc-windows-msvc
          os: windows-latest
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-24.04-arm
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: aarch64-apple-darwin
          os: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Update Rust
      run: rustup update

    - name: Add target
      run: rustup target add ${{ matrix.target }}

    - name: Build
      run: cargo build --release --locked --verbose --target ${{ matrix.target }}

    - name: Package binary 
      shell: pwsh
      run: |
        $name = "rust-mcp-server"
        $target = "${{ matrix.target }}"
        $ext = "tar.gz"
        $distDir = "dist"
        $outName = "release-$name-$target.$ext"
        New-Item -ItemType Directory -Force -Path $distDir | Out-Null

        $binaryPath = "target/$target/release/$name"
        $outputPath = "$distDir/$outName"
        tar -czf $outputPath -C (Split-Path $binaryPath) (Split-Path $binaryPath -Leaf)

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
